services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: komsync-frontend
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      BACKEND_UPSTREAM: ${BACKEND_UPSTREAM:-http://host.docker.internal:5237}
      PROD_ENV_VITE_BACKEND_ORIGIN: ${PROD_ENV_VITE_BACKEND_ORIGIN:-http://localhost:5237}
    ports:
      - "80:80"
